### ISSUE TITLE
Option unwrap on a None value within haplotype_caller_engine

### ISSUE THREAD

**Issue by AroneyS** [rhysnewell/Lorikeet#61]
Trying to run Lorikeet on a bam file against a reference like

```bash
lorikeet call \
  -r {input.genome} \
  -b {input.bam_file} \
  --calculate-fst \
  --calculate-dnds \
  --profile fast \
  --output-directory {output} \
  --threads {threads}
```

But I keep getting the following error:

```bash
[2024-12-09T05:14:24Z INFO  lorikeet] lorikeet version 0.8.2
[2024-12-09T05:14:24Z INFO  lorikeet_genome] Using min-read-aligned-percent 0%
[2024-12-09T05:14:27Z INFO  bird_tool_utils::external_command_checker] Found samtools version 1.21 
[2024-12-09T05:14:27Z INFO  lorikeet_genome::processing::lorikeet_engine] Processing short reads...
thread '<unnamed>' panicked at src/haplotype/haplotype_caller_engine.rs:1992:14:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at /home/conda/.cargo/registry/src/index.crates.io-6f17d22bba15001f/scoped_threadpool-0.1.9/src/lib.rs:236:13:
Thread pool worker panicked
```

**Comment by AroneyS** [comment]
My mistake, wrong reference
